### ISSUE TITLE
The site for searching logos is not found

### ISSUE THREAD

**Issue by RavinduSachintha** [abranhe/programming-languages-logos#11]
[languages.abranhe.com](https://languages.abranhe.com/)

It will be more helpful if you can maintain that site as an automated GitHub page. Then you will not need to worry about it at all. Just a suggestion. :wink:

**Comment by abranhe** [comment]
Thanks, it was hosted on Netlify and I moved the domain to Vercel, I'll take care of fixing it. By the way the repo for the site is https://github.com/abranhe/programming-languages-logos-site

**Comment by RavinduSachintha** [comment]
:+1:

**Comment by abranhe** [comment]
This was a one-minute fix, just changing the DNS records and I totally forgot it, but it has been fixed now, therefore I am closing this issue.
