### ISSUE TITLE
C++ Icon

### ISSUE THREAD

**Issue by TomSputz** [abranhe/programming-languages-logos#3]
Why have you chosen the purple warped C++ icon? Just [googling C++ off the cuff](https://www.google.co.uk/search?q=c%2B%2B+logo&tbm=isch), I can't find any instances of that icon being used somewhere else

**Comment by abranhe** [comment]
Thanks, @TomSputz I also found that the [isocpp official logo](https://isocpp.org/home/terms-of-use) it is also blue, we should change that, but the pink/purple C++ logo was inspire by color represented by [linguistic](https://github.com/github/linguist) of the C++ programming language.

We also will need to work on a new C logo

https://cdn.jsdelivr.net/npm/@programming-languages-logos/c@0.0.2/c_128x128.png

![C++ v0.0.2](https://cdn.jsdelivr.net/npm/@programming-languages-logos/c@0.0.2/c_128x128.png)
